### ISSUE TITLE
Error: Response code 403 forbidden

### ISSUE THREAD

**Issue by jforaker** [lucaperret/kap-now#5]
Got this on my first try, on a very small gif. Tried to quit and re-opened kap after I added the Now plugin but didnt help:

![image](https://user-images.githubusercontent.com/2042031/37246747-66d7b15c-247d-11e8-902d-5b6717a79d36.png)

```
Error: Response code 403 (Forbidden)
    at stream.catch.then.data (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/got/index.js:341:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

**Comment by jforaker** [comment]
Token was misconfigured, closing.
